"""init

Revision ID: 9ed2ac619d0a
Revises: 
Create Date: 2026-05-25 10:01:36.743734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed2ac619d0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nome', sa.String(), nullable=False),
    sa.Column('cliente_email', sa.String(), nullable=False),
    sa.Column('tipo_solicitacao', sa.String(), nullable=False),
    sa.Column('valor_patrimonio', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cliente_email'), 'clientes', ['cliente_email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('eventos_processados',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_eventos_processados_event_id'), 'eventos_processados', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_processados_event_id'), table_name='eventos_processados')
    op.drop_table('eventos_processados')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cliente_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
